name: Build YouTubePlus

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YouTubePlus
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.6
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Setup Theos
        uses: actions/checkout@v4.1.6
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-16.5-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}

      - name: Download iOS 16.5 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git && cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.6
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Tweak YouTubePlus
        id: build_package
        run: |
          (echo export PATH="/usr/local/opt/make/libexec/gnubin:$PATH" >> ~/.bash_profile)
          source ~/.bash_profile
          cd ${{ github.workspace }}/main
          make package FINALPACKAGE=1
          Version=$(grep '^Version' control | cut -d' ' -f2)
          echo "Version=$Version" >> $GITHUB_OUTPUT
          echo "==> Built v$Version Successfully."
          cd ${{ github.workspace }}/main/packages
          tweakName=$(ls *.deb)
          echo "tweakName=${tweakName}" >> $GITHUB_OUTPUT
          tar -xf ${tweakName}; tar -xf data.tar.*
          mkdir output
          cp -r Library/Application\ Support/*.bundle output
          cp -r Library/MobileSubstrate/DynamicLibraries/*.dylib output
          cp -r Library/Frameworks/*.framework output

        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: YouTubePlus
          path: main/packages/output/*
          if-no-files-found: error
